module.exports = {
  database: {
    db_url: "mongodb://localhost:27017/experiences",
  },
  base_url: `http://localhost:${process.env.PORT}`,
  app_url: `http://localhost:3500`,
  aws: {
    accessKeyId: process.env.AWS_KEY,
    secretAccessKey: process.env.AWS_SECRET,
    bucket: "askurdoctor",
  },
  rekognition: {
    collection: `Exp-${process.env.ENV}`,
  },
  db_username: "",
  db_password: "",
  db_host: process.env.DB_HOST,
  db_name: process.env.DB_NAME,
  jwt_secret: process.env.JWT_SECRET,
  forex: process.env.FOREX,
  key: process.env.ENCRYPTION_KEY,
  ivString: process.env.IV_STRING,
  sendgrid_api_key: process.env.SENDGRID_API_KEY,
  stripe_api_key: process.env.STRIPE_API_KEY,
  stripe_shared_secret: process.env.STRIPE_SHARED_SECRET,
  razor_api_key: process.env.RAZORPAY_API,
  razor_shared_secret: process.env.RAZORPAY_SECRET,
  daily_api_key: process.env.DAILY_API_KEY,
  twilio_account_ssid: process.env.TWILIO_ACCOUNTSSID,
  twilio_auth_token: process.env.TWILIO_AUTH_TOKEN,
  demo_mode: process.env.DEMO_MODE === "true",
  email: {
    from: "vinmein2012@gmail.com",
  },
  sendGrid_templates: {
    email_verify: "d-e836ddba7652470e83befd2e3b6cd4c3",
    reset_password: "d-682d28653e314f4abf36c2ae63ca00eb",
  },
  pk_config: [
    "aws.accessKeyId",
    "aws.secretAccessKey",
    "forex",
    "key",
    "ivString",
    "daily_api_key",
    "sendgrid_api_key",
    "stripe_api_key",
    "stripe_shared_secret",
    "razor_api_key",
    "razor_shared_secret",
  ],
};
