module.exports = {
  SEGMENT: 3,
  ACCBASE: 1000000,
  UPLOAD_ACL: "public-read",
  RESOURCE: {
    DELIMITER: "resources",
  },
  HOURS: 2,
  HEALTHOS: "https://www.healthos.co/",
  DAILY_URL: "https://api.daily.co/",
  DAILY_DELIMITER: "ASK-",
  MINIMUM_TOP: 1000,
  STRIPE_URL: "https://api.stripe.com",
  FOREX_BASEURL: "https://fcsapi.com/api-v2/forex/base_latest",
  FOREX_BASE_CURRENCY: "USD",
  FOREX_BASE_UNIT: 1,
  CURRENCY_DECIMAL: 2,
  MOBILE_NUMBER: "+18142059661",
  TOKEN_EXPIRES_IN: {
    SIGNIN: "10d",
    REFRESH: "90d",
  },
  EVENTS: {
    CATEGORY: {
      VALUES: ["CAMPAIGN", "PAYMENT", "USER"],
      ENUM: { CAMPAIGN: "CAMPAIGN", PAYMENT: "PAYMENT", USER: "USER" },
    },
    TYPE: {
      VALUES: [
        "CAMPAIGN.CREATED",
        "CAMPAIGN.PUBLISHED",
        "CAMPAIGN.REQUESTED",
        "CAMPAIGN.APPROVED",
        "CAMPAIGN.REJECTED",
        "CAMPAIGN.SUBMITTED",
        "CAMPAIGN.MODERATED",
        "CAMPAIGN.CLOSED",
        "CAMPAIGN.CANCELED",
        "PAYMENT.APPROVED",
        "PAYMENT.REJECTED",
        "PAYMENT.FAILED",
        "PAYMENT.REQUESTED",
        "USER.CREATED",
        "USER.PASSWORD.UPDATED",
        "USER.PASSWORD.RESETED",
        "USER.ACCOUNT.TERMINATED",
      ],
      ENUM: {
        CAMPAIGN: {
          CREATED: "CAMPAIGN.CREATED",
          PUBLISHED: "CAMPAIGN.PUBLISHED",
          REQUESTED: "CAMPAIGN.REQUESTED",
          APPROVED: "CAMPAIGN.APPROVED",
          REJECTED: "CAMPAIGN.REJECTED",
          SUBMITTED: "CAMPAIGN.SUBMITTED",
          MODERATED: "CAMPAIGN.MODERATED",
          CLOSED: "CAMPAIGN.CLOSED",
          CANCELED: "CAMPAIGN.CANCELED",
        },
        PAYMENT: {
          APPROVED: "PAYMENT.APPROVED",
          REJECTED: "PAYMENT.REJECTED",
          FAILED: "PAYMENT.FAILED",
          REQUESTED: "PAYMENT.REQUESTED",
        },
        USER: {
          CREATED: "USER.CREATED",
          PASSWORD: {
            UPDATED: "USER.PASSWORD.UPDATED",
            RESETED: "USER.PASSWORD.RESETED",
            TERMINATED: "USER.ACCOUNT.TERMINATED",
          },
        },
      },
    },
  },
  ROLE: {
    VISTIORS: "VISTIORS",
    DOCTORS: "DOCTORS",
    ADMIN: "ADMIN",
    MODERATOR: "MODERATOR",
  },
  MODULE_CODE: {
    USER: 1,
    RESOURCE: "RES1",
    SCHEDULER: "SCH",
    PATIENT: "PAT",
    APPOINTMENT: "APP",
    QUALIFICATION: "QUAL",
    DRUG: "DRG",
    VIDEO: "VID",
    RX: "RX",
    WALLET: 3,
    ACCOUNTS: 7,
    CONFIGURATION: 5,
    INIT: 8,
    NOTIFICATION: 9,
    PAYMENT: "PAY",
    CATEGORY: "CAT1",
    ANALYTICS: "ANLY1",
    HOOKS: "HOOKS",
    STRIPE: "STRIPE",
  },
  OPERATION_CODE: {
    CREATE: 1,
    READ: 2,
    DELETE: 3,
    UPDATE: 4,
    AUTH: 5,
    UPLOAD: 6,
    REGISTER: 7,
    COMPARE: 8,
    FETCH: 9,
  },
  ERROR_TYPE: {
    GENERIC: 0,
    SYSTEM: 9,
  },
  FINANCIAL_ACCOUNT: {
    DEFAULT_ACCOUNT_TYPE: "SAVINGS",
  },
  FIREBASE: {
    SEND_API_ERROR_CODES: {
      REGTOKEN_NOT_REGISTERED: "messaging/registration-token-not-registered",
    },
    NOTIFICATION_TYPE: {
      SILENT: "silent",
      NORMAL: "normal",
    },
  },
  UPLOAD_MAX_FILESIZE: 1000 * 1000 * 12,
  COMMISSION: {
    DEFAULT: 15,
    METRIC: "PERCENT",
  },
};
